### ISSUE TITLE
edge 插件不能返回图片地址

### ISSUE THREAD

**Issue by LeanFly** [icret/EasyImage-Browser-Extension#3]
![image](https://github.com/icret/EasyImage-Browser-Extension/assets/18253047/e0a37a93-1a4c-4147-8417-75071b223db3)
提交图片后一直停留在上传中，未能返回图片地址。去管理后台发现是成功状态。

**Comment by icret** [comment]
查看下你的网络问题吧，或者环境问题。

**Comment by BlackWhite2000** [comment]
看下是不是报错 Uncaught SyntaxError: "[object Object]" is not valid JSON 
如果是可以用这个版本：https://github.com/BlackWhite2000/EasyImage-Browser-Extension
直接加载文件夹就好

**Comment by LeanFly** [comment]
> 看下是不是报错 Uncaught SyntaxError: "[object Object]" is not valid JSON 如果是可以用这个版本：https://github.com/BlackWhite2000/EasyImage-Browser-Extension 直接加载文件夹就好

感谢，确实同样的报错，加载新的插件后解决
